pipeline:
  build:
    image: golang
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o web main.go
    when:
      branch: master
  deploy:
    image: plugins/docker
    repo: swqqh/drone-test # docker仓库地址
    username: swqqh
    password: swqqh@qq.com
    tag: ${DRONE_COMMIT_BRANCH##deployed/}-${DRONE_COMMIT_SHA:0:8}
    when:
      branch: master